main = ".open-next/worker.js"
name = "bigtime"
compatibility_date = "2025-12-23"
compatibility_flags = ["nodejs_compat"]
[assets]
directory = ".open-next/assets"
binding = "ASSETS"
[[routes]]
pattern = "bigtime.pw"
custom_domain = true